### ISSUE TITLE
Improper zoom cursor calculation on ROTATED images

### ISSUE THREAD

**Issue by softpretzel** [wittlock/ngx-image-zoom#56] opened 2020-02-25 19:28 UTC
When image is rotated and the user zooms, cursor calculation rotates with image, causing improper cursor calculation. 

ex. Image is rotated 180 degrees, cursor calculation is flipped 180 degrees. Moving mouse UP on a 180 degree rotated image will move the cursor DOWN.

I believe this issue is related to the setZoomPosition() function.

**Comment by wittlock** [comment] 2020-02-25 19:56
I do think I know what the problem is but I'm still pondering a good approach to fix it. Could you maybe share what CSS you are applying to the image to rotate it that I can use as a reproduction case? Post it over in #41 - I'll close this as a duplicate to keep things tidy.

**Closed by wittlock** 2020-02-25 19:56 UTC
