### ISSUE TITLE
Angular CLI 7 Version

### ISSUE THREAD

**Issue by kernelport** [wittlock/ngx-image-zoom#23] opened 2018-11-09 13:00 UTC
I made an Angular CLI Lib of your lib:
https://github.com/kernelport/ngx-image-zoom-dev
And add options styleWidth and styleHeight to scale  the 'thumbImage' size
This was an feature request in #6 
It is not possible to make a pull request because it is a new project. But you can review this commit:
https://github.com/kernelport/ngx-image-zoom-dev/commit/9ae8110596de56dfc0dfb6ddf1a00332a8b1091a

**Comment by ME-Studio** [comment] 2018-11-20 12:39
Any update?

**Comment by kernelport** [comment] 2018-11-20 14:20
It works, see example project
https://github.com/kernelport/ngx-image-zoom-test

**Comment by wittlock** [comment] 2018-11-20 21:11
Thank you. I'll check out your solution when adding it into this project for sure. It looks nice and clean. But to keep discussions in one place I'll close this as a duplicate of #6 , but that doesn't mean I don't appreciate you letting me know about your implementation.

**Closed by wittlock** 2018-11-20 21:11 UTC

**Comment by nicoesiea** [comment] 2022-11-15 08:44
What is niz-NgxImageZoom on the template? Should it be <ngx-image-zoom> tag instead?

**Comment by nicoesiea** [comment] 2022-11-15 08:53
I do not understand. The library is well loaded, and the thumbnail image picture is visible, but there is no lens when I put the mouse over the picture... I'm using angular 7... with TypeScript ~3.1.6
Any idea?
