### ISSUE TITLE
Ivy peer dependencies #refactor_for_angular9

### ISSUE THREAD

**Issue by sNohz** [wittlock/ngx-image-zoom#54] opened 2020-02-21 09:39 UTC
I'm getting this message when running my angular 9 project.

```
ERROR in The target entry-point "ngx-image-zoom" has missing dependencies:
 - @angular/core
 - @angular/common
```

**Comment by wittlock** [comment] 2020-02-23 20:01
Duplicate of #50 - release coming shortly that adresses this with version 0.5.0

**Closed by wittlock** 2020-02-23 20:01 UTC
Labels: duplicate
